name: Flyway-AutoPilot-Simple-Pipeline-Windows

trigger: 
  branches:
    include:
      - main
  paths:
    include:
      - migrations/*

pool:
  name: "default" # To be set when a self-hosted agent pool is to be used alongside this pipeline
  #vmImage: "" # To be used when a microsoft-hosted agent is used alongside this pipeline (Such as ubuntu-latest/windows-latest)

variables:

  # This is the relative path to the migrations folder in your project, such as:
  # $(System.DefaultWorkingDirectory)\project
  # The default is to have the migrations folder in the same directory as the yml file
  WORKING_DIRECTORY: $(System.DefaultWorkingDirectory)
  system.debug: false # Set this to true to enable verbose logging on your pipeline run
  
  # Optional: Side Task #2 -For added security, the below could be added to a variable group and marked as secure. Try this out in future once you get the pipeline running.
  group: "redgate_global_vars" # FLYWAY_EMAIL/FLYWAY_TOKEN
  #FLYWAY_LICENSE_KEY: "" # Deprecated Authentication Method. Use PATs instead and place securely in above library group
  BASELINE_VERSION: "001"

  # Optional - For Microsoft Hosted Agents, it's necessary to ensure Flyway is installed on each run. Therefore, the below variables are required
  FLYWAY_CLI_INSTALL_CHECK: "false" # Setting to false will skip the Flyway CLI check step
  FLYWAY_VERSION: "10.18.2" # This outlines the version of Flyway CLI that will be downloaded if no Flyway CLI is detected on the target agent
  REDGATE_FLYWAY_DIFF_VERB: "true" # Enables Alpha Diff Verbs within Flyway CLI

  # Optional: Side Task #1 - Setup Flyway Pipeline Integration - https://flyway.red-gate.com/ For More Details
  FLYWAY_PUBLISH_RESULT: "true" # Set this value to true to enable Flyway Pipelines and track your releases centrally!
  # FLYWAY_LICENSE_KEY: "" # Set in Library Group 'redgate_global_vars', enable this variable if in plaintext
  # FLYWAY_VERSION_DESCRIPTION "FlywayCLIAutomatedScript" # Set in Library Group 'redgate_global_vars', enable this variable if in plaintext

stages:
  - stage: Build # Tip - The build stage is a great way of gaining quick early feedback about upcoming releases. It simply needs to point to an empty database to function.
    displayName: Build Stage 
    jobs:
    - job: Build
      variables: # Tip - For sensitive variables, these can be made into a secret by clicking the Variables button in top right corner of the YAML pipeline editor.
        # Variables Expected - FLYWAY_LICENSE_KEY/FLYWAY_VERSION_DESCRIPTION
      - group: redgate_global_vars
        # Variables Expected - BUILD_DATABASE_JDBC/BUILD_DATABASE_USER/BUILD_DATABASE_PASSWORD/TARGET_DATABASE_JDBC/TARGET_DATABASE_USER/TARGET_DATABASE_PASSWORD
      - group: redgate_build_vars # 
      - name: DATABASE_NAME
        value: "MyDatabaseName" # Name of the target database. In this case an empty disposable database we can use for build testing.
      - name: FLYWAY_PROJECT_PATH
        value: "$(WORKING_DIRECTORY)"
      - name: TARGET_ENVIRONMENT
        value: "build" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      - name: executeBuild
        value: true # Turn to false to skip the build stage tasks

      steps:
         # Pre-Req - Check if Flyway CLI Installed and Available on Agent
        - task: PowerShell@2
          displayName: 'Flyway CLI - Install Check'
          condition: eq(variables['FLYWAY_CLI_INSTALL_CHECK'], true)
          inputs:
            targetType: 'inline'
            script: |
                    $scriptPath = "$(WORKING_DIRECTORY)/scripts/Flyway_DownloadAndInstallCLI.ps1"
                    if (Test-Path $scriptPath) {
                      Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
                      & $scriptPath
                      Write-Host "Updating PATH environment variable to include Flyway CLI Path"
                        Write-Host "##vso[task.prependpath]C:\FlywayCLI\flyway-$(FLYWAY_VERSION)"
                    } 
                    else {
                      Write-Host "Error: Script not found at path $scriptPath"
                      exit 1
                    }
        # Step 1- Create Build Artifact and Deploy Pending Changes #
        - task: PowerShell@2
          displayName: 'Flyway CLI - Build Validation'
          inputs:
            targetType: 'inline'
            script: |
              flyway diff info migrate info `
              "-diff.source=SchemaModel" `
              "-diff.target=migrations" `
              "-diff.buildEnvironment=$(TARGET_ENVIRONMENT)" `
              "-environment=$(TARGET_ENVIRONMENT)" `
              "-environments.$(TARGET_ENVIRONMENT).user=$(TARGET_DATABASE_USER)" `
              "-environments.$(TARGET_ENVIRONMENT).password=$(TARGET_DATABASE_PASSWORD)" `
              "-environments.$(TARGET_ENVIRONMENT).provisioner=clean" `
              "-diff.artifactFilename=$(System.ArtifactsDirectory)\Artifacts\Flyway.$(DATABASE_NAME).differences-$(get-date -f yyyyMMdd).zip" `
              -outputType="" `
              -configFiles="$(WORKING_DIRECTORY)\flyway.toml" `
              -schemaModelLocation="$(WORKING_DIRECTORY)\schema-model\" `
              -locations="filesystem:$(WORKING_DIRECTORY)\migrations" `
              "-flywayServicePublish.publishReport=$(FLYWAY_PUBLISH_RESULT)" `
              "-reportEnabled=$(FLYWAY_PUBLISH_RESULT)"
            pwsh: false
          continueOnError: false
          condition: eq(variables['executeBuild'], true)
          env:
            FLYWAY_EMAIL: "$(FLYWAY_EMAIL)" # Task Variables can also be passed if Library Group method not used
            FLYWAY_TOKEN: "$(FLYWAY_TOKEN)" # Secure Variables, such as PATs, can be passed as environment variables for added security

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(WORKING_DIRECTORY)'
            Contents: |
              !flyway-*/**/*
              !.git/**/*
              !.git*/**/*
              **/schema-model/**/*
              **/migrations/**/*
              **/backups/**/*
              **/flyway.toml
              **/Filter.scpf
            TargetFolder: '$(System.ArtifactsDirectory)'

        - task: PublishBuildArtifacts@1 # This step publishes all the validated Flyway Project files as a build artifact
          displayName: 'Publish Build Artifact'
          inputs:
            ArtifactName: 'Flyway-CI-$(Build.BuildId)'
            PathtoPublish: '$(System.ArtifactsDirectory)'

  - stage: Test
    displayName: Test Stage
    dependsOn: Build
    variables: # Tip - For sensitive variables, these can be made into a secret by clicking the Variables button in top right corner of the YAML pipeline editor.
      DATABASE_NAME: "MyDatabaseName" # Name of the target database. In this case an empty disposable database we can use for build testing.
      TARGET_ENVIRONMENT: "test" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      TARGET_DATABASE_USERNAME: "Redgate" # Optional - If SQL Authentication is used, provide the relevant database username. Otherwise, leave blank
      TARGET_DATABASE_PASSWORD: "MyPassword" # Optional - If SQL Authentication is used, provide the relevant database password. Otherwise, leave blank
      REPORT_ENVIRONMENT: "check" # This variable refers to the environment name present in the Flyway Projects TOML file. Use Flyway Desktop to check and change this value if required.
      REPORT_DATABASE_USERNAME: "Redgate" # Optional - If SQL Authentication is used, provide the relevant database username. Otherwise, leave blank
      REPORT_DATABASE_PASSWORD: "MyPassword" # Optional - If SQL Authentication is used, provide the relevant database password. Otherwise, leave blank
      pauseForCodeReview: false
      generateReport: true                     #Turn on to enable the Check Report
      #- group: ${{stage.variableGroupName}}
    jobs:
    - job: ChangeReport
      displayName: "Flyway - Pre Release Change Report"
      condition: eq(variables['generateReport'], true)
      variables:
        EXAMPLE: ""
      #- group: ${{stage.variableGroupName}}
      #- group: pipeline_flyway_vars
      steps:
                 # Pre-Req - Check if Flyway CLI Installed and Available on Agent
        - task: PowerShell@2
          displayName: 'Flyway CLI - Install Check'
          condition: eq(variables['FLYWAY_CLI_INSTALL_CHECK'], true)
          inputs:
            targetType: 'inline'
            script: |
               $scriptPath = "$(WORKING_DIRECTORY)/scripts/Flyway_DownloadAndInstallCLI.ps1"
                    if (Test-Path $scriptPath) {
                      Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
                      & $scriptPath
                      Write-Host "Updating PATH environment variable to include Flyway CLI Path"
                        Write-Host "##vso[task.prependpath]C:\FlywayCLI\flyway-$(FLYWAY_VERSION)"
                    } 
                    else {
                      Write-Host "Error: Script not found at path $scriptPath"
                      exit 1
                    }
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'Flyway-CI-$(Build.BuildId)'
            downloadPath: '$(System.ArtifactsDirectory)'
        
        - script: |
              flyway check -dryrun -changes -drift info -environment="$(TARGET_ENVIRONMENT)" -user="$(TARGET_DATABASE_USERNAME)" -password="$(TARGET_DATABASE_PASSWORD)" -check.buildEnvironment="$(REPORT_ENVIRONMENT)" -environments.$(REPORT_ENVIRONMENT).user="$(REPORT_DATABASE_USERNAME)" -environments.$(REPORT_ENVIRONMENT).password="$(REPORT_DATABASE_PASSWORD)" -licenseKey="$(FLYWAY_LICENSE_KEY)" -configFiles="$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\flyway.toml" -locations="filesystem:$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\migrations" "-reportEnabled=true" "-reportFilename=$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\reports\$(DATABASE_NAME)-Run-$(Build.BuildId)-Check-Report.html" -email="$(FLYWAY_EMAIL)" -token="$(FLYWAY_TOKEN)"
          workingDirectory: '$(WORKING_DIRECTORY)'
          continueOnError: false
          displayName: 'Flyway Check Report'
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Check Report'
          condition: always()
          inputs:
            ArtifactName: 'Flyway-CD-Reports-$(Build.BuildId)'
            PathtoPublish: '$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\reports\$(DATABASE_NAME)-Run-$(Build.BuildId)-Check-Report.html'
        
        - task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1 #This is an optional task that can make viewing the Check report much easier in each run. Disable if required.
          displayName: 'Publish HTML Report'
          inputs:
            reportDir: '$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\reports\$(DATABASE_NAME)-Run-$(Build.BuildId)-Check-Report.html'

    - job: CodeReview
      displayName: Code Review
      dependsOn: ChangeReport
      pool: server
      steps:
        - task: ManualValidation@0
          condition: eq(variables['pauseForCodeReview'], true)
          displayName: 'Review Change Report Prior To Release'
          timeoutInMinutes: 4320 
          inputs:
            notifyUsers: |
              user@email.com
              example@example.com
            instructions: 'Review changes'
        
    - job: Deploy
      displayName: "Deploy"
      dependsOn: CodeReview
      variables:
        EXAMPLE: ""
      steps:
                 # Pre-Req - Check if Flyway CLI Installed and Available on Agent
        - task: PowerShell@2
          displayName: 'Flyway CLI - Install Check'
          condition: eq(variables['FLYWAY_CLI_INSTALL_CHECK'], true)
          inputs:
            targetType: 'inline'
            script: |
               $scriptPath = "$(WORKING_DIRECTORY)/scripts/Flyway_DownloadAndInstallCLI.ps1"
                    if (Test-Path $scriptPath) {
                      Write-Host "Script found. Running Flyway_DownloadAndInstallCLI.ps1..."
                      & $scriptPath
                      Write-Host "Updating PATH environment variable to include Flyway CLI Path"
                        Write-Host "##vso[task.prependpath]C:\FlywayCLI\flyway-$(FLYWAY_VERSION)"
                    } 
                    else {
                      Write-Host "Error: Script not found at path $scriptPath"
                      exit 1
                    }
        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: 'Flyway-CI-$(Build.BuildId)'
            downloadPath: '$(System.ArtifactsDirectory)'
        - task: PowerShell@2
          displayName: 'Flyway CLI - Migrate'
          condition: succeeded()
          continueOnError: false
          inputs:
            targetType: 'inline'
            workingDirectory:
            script: |
              flyway info migrate info `
              -environment="$(TARGET_ENVIRONMENT)" `
              -user="$(TARGET_DATABASE_USERNAME)" `
              -password="$(TARGET_DATABASE_PASSWORD)" `
              -errorOverrides=S0001:0:I- `
              -baselineOnMigrate=true `
              -baselineVersion="$(BASELINE_VERSION)" `
              -configFiles="$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\flyway.toml" `
              -locations="filesystem:$(System.ArtifactsDirectory)\Flyway-CI-$(Build.BuildId)\migrations" `
              "-flywayServicePublish.publishReport=$(FLYWAY_PUBLISH_RESULT)" `
              "-reportEnabled=$(FLYWAY_PUBLISH_RESULT)"
          env:
            FLYWAY_EMAIL: "$(FLYWAY_EMAIL)" # Task Variables can also be passed if Library Group method not used
            FLYWAY_TOKEN: "$(FLYWAY_TOKEN)" # Secure Variables, such as PATs, can be passed as environment variables for added security